Update bin/test to check for cf cli
[#161467989](https://www.pivotaltracker.com/story/show/161467989)

diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -5,6 +5,11 @@ if [[ ! -r "${CONFIG}" ]]; then
   exit 1
 fi
 
+if [[ -z "$(command -v cf)" ]]; then
+  echo "FAIL: Missing cf cli"
+  exit 1
+fi
+
 if [[ -z "$(command -v ginkgo)" ]]; then
   echo "FAIL: Missing ginkgo cli"
   exit 1
